### ISSUE TITLE
Amount = Intensity

### ISSUE THREAD

**Issue by ztffn** [pyalot/webgl-heatmap#18]
If each several points are added to the map with the same coordinates, shouldn't the whole point of the heatmap be that the intensity then automatically gets stronger at that coordinate.
I can add 100 points to the map with Intensity=1 and it just looks as it has gotten one hit.

**Comment by pyalot** [comment]
Addition of points is cumulative. Try adding 100 points with intensity = 0.01. There is a saturation function (https://github.com/pyalot/webgl-heatmap/blob/master/webgl-heatmap.coffee#L935) that maps an intensity to a color, it's from 0 to 1. If you add 1, you already saturated that so there's no more change for any subsequent point.

0 and 1 are chosen as the full color range because they're a meaningful set of constants for expressing "no intensity" to "full intensity".

**Comment by ztffn** [comment]
Not sure I understand this.

I add points using this structure:

heatmap.addPoint(0, 0, 25, 10 / 255); //center of map

Where intensity is set to 10/255=0.039… I still get a fully saturated single point on the heatmap as you can see here: http://steffeno.net/terranova/heatmap/ ( the code above is the larger dot in center of the map)

---

Steffen Oftedal
mail@steffeno.net mailto:mail@steffeno.net
http://steffeno.net http://steffeno.net/
+47 40225017

**Comment by pyalot** [comment]
You're adding points every animation frame. Unless you clear the map, they keep adding up.

**Comment by pyalot** [comment]
(if your map is static, don't add points every animation frame)

**Comment by ztffn** [comment]
As you might have understood already - I’m not a javascript developer. The brief readme and example isn’t really helping me much. Perhaps a stand-alone example of a static map would be a good idea?

I’ve added width and height to the initial createWebGLHeatmap() function - making it static i’m assuming, by the //comment. 

How to modify the RequestAnimationFrame to make it work as you explain seems to be beyond my skills as a novice.

Any help you might give is greatly apreciated.

---

Steffen Oftedal
mail@steffeno.net mailto:mail@steffeno.net
http://steffeno.net http://steffeno.net/
+47 40225017
